### ISSUE TITLE
QuickEdit+ hanging

### ISSUE THREAD

**Issue by woctezuma** [hateradio/qqre#1]
The QuickEdit+ function seems to bug out when I try to edit one of my posts on this page:
http://www.neogaf.com/forum/showthread.php?p=242822646

Let us say I want to edit this post and add the "test" word at the end.

![1st](http://i.imgur.com/byNsvKO.png)

I get this form, in which I add the word "test" before submitting the changes:

![2nd](http://i.imgur.com/FUKNhfQ.png)

Then I get another form (which I don't have to submit actually, because the previous change was correctly submitted, I just have to refresh the whole page). Notice that the original post is hidden:

![3rd](http://i.imgur.com/DFTwJ5z.png)

If I submit the second form, the "loading" circle is still present near the QuickEdit+ text:

![4th](http://i.imgur.com/E8BG2YZ.gif)

This happens for every post, but only the first time I want to quick-edit that post.

**Comment by hateradio** [comment]
Fixed in 10.0.1
